apiVersion: v1
kind: Service
metadata: 
  name: offer
spec:
  selector: 
    app: offer
  ports:
  - name: front-endport
    port: 1001
    targetPort: 1001
    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer
  labels:
    app: offer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer
  template:
    metadata:
      labels:
        app: offer
    spec:
      containers:
        - name: offer  
          image: masterybsr/offers:1.0
          imagePullPolicy: "IfNotPresent"
