apiVersion: v1
kind: Service
metadata: 
  name: shoe
spec:
  selector: 
    app: shoe
  ports:
  - name: front-endport
    port: 1002
    targetPort: 1002
    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe
  labels:
    app: shoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoe
  template:
    metadata:
      labels:
        app: shoe
    spec:
      containers:
        - name: shoe 
          image: masterybsr/shoes:1.0
          imagePullPolicy: "IfNotPresent"
