apiVersion: v1
kind: Service
metadata: 
  name: wishlist
spec:
  selector: 
    app: wishlist
  ports:
  - name: front-endport
    port: 1003
    targetPort: 5000
   

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist
          image: masterybsr/wishlist:1.0
          imagePullPolicy: "IfNotPresent"
