apiVersion: v1
kind: Service
metadata: 
  name: zuul-svc
spec:
  selector: 
    app: zuul
  type: NodePort
  ports:
  - name: front-endport
    port: 9999
    targetPort: 9999
    nodePort: 30008

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul
  labels:
    app: zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
        - name: zuul 
          image: masterybsr/zuul-training:1.0
          imagePullPolicy: "IfNotPresent"
