apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: my-dep
  labels: 
    type: ui
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: front-end
  template:
    metadata:
      name: my-pod
      labels: 
        app: front-end 
    spec: 
      containers:
      - name: nginx 
        image: nginx:1.22
        ports:
        - containerPort: 80    # where ur application is running 

        # container port should be same as target port 
        
